name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  desktop_drop: ^0.4.4
  dotted_border: ^2.1.0 # CR-SDRF-4: Dependencia UI para renderizado del patrón punteado del DropZone
  excel: ^4.0.6
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  intl: ^0.20.2
  pdf: ^3.12.0
  printing: ^5.14.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
